/** @type {import('tailwindcss').Config} */
export default {
    content: ['./src/**/*.{js,ts,jsx,tsx}', './stories/**/*.{js,ts,jsx,tsx}'],
    darkMode: 'class',
    theme: {
      extend: {
        colors: {
          text: {
            default: '#0F0F0F',
            secondary: '#4C4D4D',
            subdued: '#979999',
            disabled: '#B1B2B2',
            hovered: '#262626',
            success: '#008F51',
            warning: '#D99C00',
            highlight: '#0B7D8E',
            critical: '#911812',
            awaiting: '#1F56DB',
            alert: '#D99C00',
            decorative1: '#661396',
            decorative2: '#1F56DB',
          },
          action: {
            primary: '#0B7D8E',
            hovered: '#013941',
            pressed: '#001114',
            disabled: '#D9DBDB',
          },
          primitive: {
            black: '#0A0A0A',
            critical: '#C52D26',
          },
          surface: {
            default: '#FFFFFF',
            subdued: '#F0F1F2',
            hovered: '#F0F1F2',
            pressed: '#D9DBDB',
            disabled: '#E4E5E5',
            success: '#EBFAF3',
            critical: '#FAF4F4',
            highlight: '#ECF7F9',
            alert: '#FDFAF2',
            decorative1: '#F9F2FD',
            decorative2: '#F2F6FF',
            alternate: '#0A0A0A',
          },
          background: {
            default: '#F9FAFB',
            subdued: '#F0F1F2',
            icon: '#EDEDED',
            file: '#F9F9F9',
          },
          border: {
            default: '#E4E5E5',
            subdued: '#F0F1F2',
            primary: '#E3E3E3',
            disabled: '#C3C7C7',
            highlight: '#C4E8EE',
            critical: '#F7E9E9',
            decorative: '#EAD4F6',
          },
          dark: {
            text: {
              default: '#FFFFFF',
              secondary: '#F0F1F2',
              subdued: '#B1B2B2',
              disabled: '#7E8080',
              hovered: '#979999',
              success: '#C5F400',
              warning: '#FFB800',
              highlight: '#C5F400',
              critical: '#E3736D',
              awaiting: '#42A5F5',
              decorative1: '#B769E2',
              decorative2: '#739FFF',
            },
            action: {
              primary: '#C5F400',
              hovered: '#E2FF66',
              pressed: '#738F00 ',
              disabled: '#0F0F0F',
            },
            primitive: {
              black: '#1C1C1C',
              critical: '#E53935',
            },
            surface: {
              default: '#0A0A0A',
              subdued: '#191A1A',
              hovered: '#616161',
              pressed: '#757575',
              disabled: '#0F0F0F',
              success: '#4A5C00',
              alert: '#664900',
              highlight: '#4A5C00',
              critical: '#380301',
              decorative1: '#32054D',
              decorative2: '#061F59',
              alternate: '#FFFFFF',
            },
            background: {
              default: '#0F0F0F',
              subdued: '#1E1E1E',
              success: '#4A5C00',
              icon: '#333333',
              file: '#1C1C1C',
            },
            border: {
              default: '#262626',
              subdued: '#191A1A',
              primary: '#757575',
              disabled: '#0A0A0A',
              highlight: '#738F00',
              critical: '#380301',
              decorative: '#012328',
            },
            teal: {
              shade100: '#ECF7F9',
              shade200: '#C4E8EE',
              shade300: '#99DCE6',
            },
          },
        },
  
        keyframes: {
          shimmers: {
            '0%': { backgroundPosition: '200% -10%' },
            '100%': { backgroundPosition: '10% 200%' },
          },
          spin: {
            '0%': { transform: 'rotate(0deg)' },
            '100%': { transform: 'rotate(360deg)' },
          },
        },
  
        animation: {
          shimmers: 'shimmers 1.7s infinite linear forwards',
          spin: 'spin 1s linear infinite',
        },
      },
    },
    plugins: [],
  };
  